# Generated by Django 5.1.2 on 2024-11-16 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=20)),
                ('emailId', models.EmailField(max_length=254)),
                ('ticketId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accommodation', models.BooleanField()),
                ('transactionId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventName', models.CharField(max_length=50)),
                ('eventVenue', models.CharField(max_length=100)),
                ('dayNo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('eventDate', models.DateField()),
                ('eventTime', models.TimeField()),
                ('eventDesc', models.CharField(max_length=250)),
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('image', models.TextField()),
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('speakerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('competitionName', models.CharField(max_length=50)),
                ('prizeMoney', models.IntegerField()),
                ('poster', models.TextField()),
                ('competitionId', models.AutoField(primary_key=True, serialize=False)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=20)),
                ('emailId', models.EmailField(max_length=254)),
                ('registrationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competitionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.competitions')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('rollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=20)),
                ('emailId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('instagramId', models.URLField()),
                ('linkedinId', models.URLField()),
                ('teamName', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('eventid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('sponsorId', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('sponsorshipAmount', models.IntegerField()),
                ('phoneNo', models.CharField(max_length=20)),
                ('emailId', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=80)),
                ('link', models.URLField()),
                ('dealBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.team')),
            ],
        ),
    ]
