# Generated by Django 5.1.2 on 2024-10-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phoneNo', models.IntegerField()),
                ('emailId', models.EmailField(max_length=254)),
                ('ticketId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accommodation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('competitionName', models.CharField(max_length=50)),
                ('prizeMoney', models.IntegerField()),
                ('date', models.DateField()),
                ('competitionId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventName', models.CharField(max_length=50)),
                ('eventVenue', models.CharField(max_length=100)),
                ('eventTime', models.DateTimeField()),
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('rollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('phoneNo', models.IntegerField()),
                ('emailId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phoneNo', models.IntegerField()),
                ('emailId', models.EmailField(max_length=254)),
                ('registrationId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accommodation', models.BooleanField()),
                ('competitionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.competitions')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('logo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sponsorshipAmount', models.IntegerField()),
                ('phoneNo', models.IntegerField()),
                ('emailId', models.EmailField(max_length=254)),
                ('dealBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.team')),
            ],
        ),
    ]
