# Generated by Django 5.1.2 on 2024-11-17 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='eventid',
        ),
        migrations.AddField(
            model_name='event',
            name='rollNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.team'),
        ),
    ]
