# Generated by Django 5.1.2 on 2024-10-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.ImageField(upload_to='speakersImage/'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='logo',
            field=models.ImageField(upload_to='sponsorsLogo/'),
        ),
    ]
