# Generated by Django 5.1.2 on 2024-11-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_team_eventid_event_rollno'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER prevent_past_events
            BEFORE INSERT ON event_event
            FOR EACH ROW
            BEGIN
                IF CONCAT(NEW.eventDate, ' ', NEW.eventTime) < NOW() THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Cannot schedule an event in the past.';
                END IF;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS prevent_past_events;"
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER reject_duplicate_event
            BEFORE INSERT ON event_event
            FOR EACH ROW
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM event_event
                    WHERE NEW.eventDate = eventDate
                    AND NEW.eventTime = eventTime
                ) THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Event time conflicts with an existing event. Please choose a different time.';
                END IF;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS reject_duplicate_event;"
        ),
    ]
