# Generated by Django 5.1.2 on 2024-10-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_attendees_ticketid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.TextField(),
        ),
    ]
