# Generated by Django 5.1.2 on 2024-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_speakers_image_alter_sponsors_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='logo',
            field=models.TextField(),
        ),
    ]
