# Generated by Django 5.1.2 on 2024-10-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_speakers_image_alter_sponsors_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='poster',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
