# Generated by Django 5.1.2 on 2024-10-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_speakers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='phoneNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participants',
            name='phoneNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='phoneNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='phoneNo',
            field=models.CharField(max_length=20),
        ),
    ]
