# Generated by Django 5.1.2 on 2024-10-24 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_attendees_phoneno_alter_participants_phoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='ticketId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participants',
            name='registrationId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
