# Generated by Django 5.1.2 on 2024-11-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_attendees_ticketid_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER prevent_duplicate_registration
            BEFORE INSERT ON event_participants
            FOR EACH ROW
            BEGIN
                IF EXISTS (
                    SELECT 1 
                    FROM event_participants
                    WHERE name = NEW.name
                      AND emailId = NEW.emailId
                      AND phoneNo = NEW.phoneNo
                      AND competitionId_id = NEW.competitionId_id
                ) THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Duplicate registration: The participant is already registered for this competition.';
                END IF;
            END;
            """
        )
    ]
