# Generated by Django 5.1.2 on 2024-10-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_competitions_poster'),
        ('event', '0005_alter_attendees_ticketid_and_more'),
    ]

    operations = [
    ]
