# Generated by Django 5.1.2 on 2024-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_merge_20241030_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventDesc',
            field=models.CharField(default='hello', max_length=250),
            preserve_default=False,
        ),
    ]
