# Generated by Django 5.1.2 on 2024-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_eventdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dayNo',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventDate',
            field=models.DateField(default='2025-10-03'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='eventTime',
            field=models.TimeField(),
        ),
    ]
