# Generated by Django 5.1.2 on 2024-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_dayno_event_eventdate_alter_event_eventtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('image', models.TextField()),
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
