# Generated by Django 5.1.2 on 2024-10-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='link',
            field=models.URLField(default='https://www.google.com/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsors',
            name='title',
            field=models.CharField(default='hello', max_length=80),
            preserve_default=False,
        ),
    ]
