# Generated by Django 5.1.2 on 2024-11-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_sponsors_link_sponsors_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='instagramId',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='linkedinId',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
