# Generated by Django 5.1.2 on 2024-11-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_team_instagramid_team_linkedinid'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamName',
            field=models.CharField(default='marketing', max_length=50),
            preserve_default=False,
        ),
    ]
