# Generated by Django 5.1.2 on 2024-11-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='id',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
