# Generated by Django 5.1.2 on 2024-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_transactions_id_alter_transactions_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendees',
            name='transactionId',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
