# Generated by Django 5.1.2 on 2024-11-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_attendees_transactionid_delete_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='accommodation',
        ),
    ]
