# Generated by Django 5.1.2 on 2024-11-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_remove_participants_accommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakers',
            name='id',
        ),
        migrations.AddField(
            model_name='speakers',
            name='speakerId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsors',
            name='sponsorId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
