# Generated by Django 5.1.2 on 2024-11-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_remove_speakers_id_speakers_speakerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='sponsorId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
